DROP TABLE IF EXISTS mpa_rating, film, genre, film_genre, users, likes, friendship;

CREATE TABLE IF NOT EXISTS public.mpa_rating (
	mpa_rating_id INTEGER NOT NULL PRIMARY KEY,
	mpa_value CHARACTER VARYING(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.film (
	film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	film_name CHARACTER VARYING(150) NOT NULL,
	description CHARACTER VARYING(500),
	release_date DATE NOT NULL,
	duration INTEGER NOT NULL,
	mpa_rating_id INTEGER NOT NULL REFERENCES public.mpa_rating(mpa_rating_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.genre (
	genre_id INTEGER NOT NULL PRIMARY KEY,
	genre_name CHARACTER VARYING(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.film_genre (
	film_id BIGINT NOT NULL REFERENCES public.film(film_id) ON DELETE CASCADE ON UPDATE CASCADE,
	genre_id INTEGER NOT NULL REFERENCES public.genre(genre_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT COMPOSITE_KEY_FILM_GENRE PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS public.users (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email CHARACTER VARYING(100) NOT NULL,
	login CHARACTER VARYING(50) NOT NULL,
	user_name CHARACTER VARYING(50),
	birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.likes (
	film_id BIGINT NOT NULL REFERENCES public.film(film_id) ON DELETE CASCADE ON UPDATE CASCADE,
	user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT COMPOSITE_KEY_LIKES PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.friendship (
	inviter_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	acceptor_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	confirmation_status BOOLEAN NOT NULL DEFAULT false, 
	CONSTRAINT COMPOSITE_KEY_FRIENDSHIP PRIMARY KEY (inviter_id, acceptor_id)
);

INSERT INTO public.mpa_rating (mpa_rating_id,mpa_value)
    VALUES (1,'G'), (2,'PG'), (3,'PG-13'), (4,'R'), (5,'NC-17');
   
INSERT INTO public.genre (genre_id,genre_name)
    VALUES (1,'Комедия'), (2,'Драма'), (3,'Мультфильм'), (4,'Триллер'), (5,'Документальный'), (6,'Боевик');